//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMposter.Controller {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class ControllerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControllerSettings defaultInstance = ((ControllerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControllerSettings())));
        
        public static ControllerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.4")]
        public double haarScaleFactor {
            get {
                return ((double)(this["haarScaleFactor"]));
            }
            set {
                this["haarScaleFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int haarMinNeighbours {
            get {
                return ((int)(this["haarMinNeighbours"]));
            }
            set {
                this["haarMinNeighbours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Face\\haarcascade_frontalface_alt2.xml")]
        public string haarCascadeFile {
            get {
                return ((string)(this["haarCascadeFile"]));
            }
            set {
                this["haarCascadeFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int haarMinFaceImageDivider {
            get {
                return ((int)(this["haarMinFaceImageDivider"]));
            }
            set {
                this["haarMinFaceImageDivider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int interactionTableFaceRenewalAnnimationMilisecondsDuration {
            get {
                return ((int)(this["interactionTableFaceRenewalAnnimationMilisecondsDuration"]));
            }
            set {
                this["interactionTableFaceRenewalAnnimationMilisecondsDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int interactionTableFaceCaptureSecondInterval {
            get {
                return ((int)(this["interactionTableFaceCaptureSecondInterval"]));
            }
            set {
                this["interactionTableFaceCaptureSecondInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int interactionTableFaceProcessSecondInterval {
            get {
                return ((int)(this["interactionTableFaceProcessSecondInterval"]));
            }
            set {
                this["interactionTableFaceProcessSecondInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int interactionTableFaceStorageMaximalNumber {
            get {
                return ((int)(this["interactionTableFaceStorageMaximalNumber"]));
            }
            set {
                this["interactionTableFaceStorageMaximalNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int consecutiveGesturesRequired {
            get {
                return ((int)(this["consecutiveGesturesRequired"]));
            }
            set {
                this["consecutiveGesturesRequired"] = value;
            }
        }
    }
}
